# Generated by Django 4.1.7 on 2023-04-12 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GRP_NM', models.CharField(blank=True, max_length=20)),
                ('GRP_STUS', models.BooleanField(default=True)),
                ('CREATED_BY', models.CharField(blank=True, max_length=24)),
                ('CREATE_TS', models.DateTimeField(auto_now_add=True)),
                ('UPDATED_BY', models.CharField(blank=True, max_length=24)),
                ('UPDATE_TS', models.DateTimeField(auto_now_add=True)),
                ('GRP_CD', models.IntegerField()),
            ],
            options={
                'db_table': 'BP_GROUPS',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EMAIL_ID', models.EmailField(max_length=50)),
                ('FRST_NM', models.CharField(max_length=255)),
                ('LST_NM', models.CharField(max_length=255)),
                ('UESR_STUS', models.BooleanField(default=True)),
                ('CREATE_TS', models.DateTimeField(auto_now_add=True)),
                ('UPDATE_TS', models.DateTimeField(auto_now_add=True)),
                ('CREATED_BY', models.CharField(blank=True, max_length=24)),
                ('UPDATED_BY', models.CharField(blank=True, max_length=24)),
                ('AUTH_GRP_CD', models.CharField(blank=True, max_length=1)),
                ('EXP_DATE', models.DateTimeField(auto_now_add=True)),
                ('GRP_ID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.group')),
            ],
            options={
                'db_table': 'BP_USERS',
            },
        ),
    ]
