# Generated by Django 4.1.7 on 2023-04-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BP_LANID', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'BP_LANID',
            },
        ),
    ]
